import 'package:flutter/material.dart';

class AppLocalizations {
  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_title': 'MindSpark Quest',
      'splash_subtitle': 'An Adventure for Curious Minds',
      'explore_rooms_title': 'Explore Magical Rooms',
      'explore_rooms_sub': 'Each room has a puzzle waiting for you!',
      'solve_puzzles_title': 'Solve Fun Puzzles',
      'solve_puzzles_sub': 'Find the right objects and light up your world!',
      'earn_rewards_title': 'Earn Stars & Rewards',
      'earn_rewards_sub': 'Collect stars, unlock rooms, and customize your world!',
      'next': 'Next',
      'back': 'Back',
      'get_started': 'Get Started',
      'lets_go': 'Let\'s Go!',
      'resume': 'Resume',
      'restart': 'Restart',
      'back_to_map': 'Back to Map',
      'parent_setup': 'Parent Setup',
      'parent_consent_title': 'Your Child\'s Privacy Matters',
      'parent_consent_desc': 'MindSpark Quest stores all data locally on this device. No personal information is shared online. This app does not provide medical diagnosis.',
      'parent_consent_check': 'I understand and give consent for my child to use this app.',
      'create_pin_title': 'Create a Parent PIN',
      'create_pin_subtitle': 'This PIN protects the parent dashboard',
      'create_profile_title': 'Create Profile',
      'whats_your_name': 'What\'s your name?',
      'age': 'Age',
      'language': 'Language',
      'start_adventure': 'Start Adventure!',
      'who_is_playing': 'Who\'s Playing?',
      'add_player': 'Add Player',
      'parent_dashboard_btn': 'Parent Dashboard 🔒',
      'attention': 'Attention',
      'impulse_control': 'Impulse Control',
      'reaction_time': 'Reaction Time',
      'suggestion': 'Suggestion',
      'recent_sessions': 'Recent Sessions',
      'completed_missions_title': 'Completed Missions',
      'diagnostic_notice': 'This app does not provide medical diagnosis. Indicators are for supportive guidance only.',
      'settings_title': 'Settings ⚙️',
      'language_sec': 'Language 🌍',
      'sound_sec': 'Sound 🔊',
      'music_vol': 'Music Volume',
      'sfx_vol': 'Sound Effects',
      'voice_instr': 'Voice Instructions',
      'accessibility_sec': 'Accessibility ♿',
      'reduce_motion': 'Reduce Motion',
      'reduce_distractors': 'Reduce Distractors',
      'colorblind_mode': 'Colorblind Mode',
      'larger_text': 'Larger Text',
      'data_sec': 'Data & Privacy 🔒',
      'clear_all': 'Reset All Data',
      'privacy_policy': 'Privacy Policy',
      'game_paused': 'Game Paused',
      'mission_complete': 'Mission Complete! 🎉',
      'new_record': 'New Record!',
      'stars': 'Stars',
      'gems': 'Gems',
      'time': 'Time',
      'accuracy': 'Accuracy',
      'hints_used': 'Hints used',
      'accuracy_great': 'Great!',
      'accuracy_good': 'Good',
      'accuracy_practice': 'Needs practice',
      'dark_room_title': 'Dark Room',
      'dark_room_desc': 'The room is dark. Can you find a way to light it up?',
      'dark_room_goal': '💡 Light up the room',
      'robot_room_title': 'Robot Room',
      'robot_room_desc': 'The robot is offline. Give it power by connecting the battery to the cable!',
      'robot_room_goal': '🤖 Power the robot',
      'door_room_title': 'Door Room',
      'door_room_desc': 'The door is locked! Find the hidden key and unlock it.',
      'door_room_goal': '🔑 Find the key and open the door',
      'skills': 'Skills',
      'skill_attention': '🎯 Attention',
      'skill_logic': '🧠 Logic',
      'skill_focus': '⚡ Focus',
      'skill_memory': '💾 Memory',
      'skill_planning': '🗺 Planning',
      'seconds': 's',
      'hint_dark_room': '💡 Hint: Tap the electrical switch to turn on the lamp!',
      'hint_robot_room': '💡 Hint: Tap the battery, then tap the power cable!',
      'hint_door_room': '💡 Hint: Tap the wooden box to find the key, then tap the key, then tap the door!',
      'hint_button': 'Hint',
      'congratulations': 'Amazing focus!',
      'pet_upgrade': 'Pet Upgrade',
      'my_treasures': 'My Treasures ✨',
      'skins_tab': 'Skins 🎨',
      'rooms_tab': 'Rooms 🏠',
      'pets_tab': 'Pets 🐾',
      'equipped': 'Equipped',
      'use': 'Use',
      'locked': 'Locked',
      'improving': '↑ Improving',
      'steady': '→ Steady',
      'great': '↑ Great',
      'parent_pin_prompt': 'Enter Parent PIN to Access Dashboard',
      'invalid_pin': 'Invalid PIN. Try again!',
      'keep_trying': 'Keep Trying! 💪',
      'practice_message': 'Practice helps us grow our focus muscles!',
      'go_to_map': 'Go to World Map',
      'play_again': 'Play Again',
      'try_again': 'Try Again',
    },
    'fr': {
      'app_title': 'MindSpark Quest',
      'splash_subtitle': 'Une aventure pour les esprits curieux',
      'explore_rooms_title': 'Explorez des pièces magiques',
      'explore_rooms_sub': 'Chaque pièce recèle un puzzle qui t\'attend !',
      'solve_puzzles_title': 'Résolvez des énigmes amusantes',
      'solve_puzzles_sub': 'Trouvez les bons objets et illuminez votre monde !',
      'earn_rewards_title': 'Gagnez des étoiles et des récompenses',
      'earn_rewards_sub': 'Collectionnez des étoiles, débloquez des pièces et personnalisez votre monde !',
      'next': 'Suivant',
      'back': 'Retour',
      'get_started': 'Commencer',
      'lets_go': 'C\'est parti !',
      'resume': 'Reprendre',
      'restart': 'Recommencer',
      'back_to_map': 'Retour à la carte',
      'parent_setup': 'Configuration Parent',
      'parent_consent_title': 'La vie privée de votre enfant compte',
      'parent_consent_desc': 'MindSpark Quest stocke toutes les données localement sur cet appareil. Aucune information personnelle n\'est partagée en ligne. Cette application ne fournit pas de diagnostic médical.',
      'parent_consent_check': 'Je comprends et consens à l\'utilisation de l\'application par mon enfant.',
      'create_pin_title': 'Créer un code PIN parent',
      'create_pin_subtitle': 'Ce code PIN protège le tableau de bord parent',
      'create_profile_title': 'Créer un profil',
      'whats_your_name': 'Comment t\'appelles-tu ?',
      'age': 'Âge',
      'language': 'Langue',
      'start_adventure': 'Démarrer l\'aventure !',
      'who_is_playing': 'Qui joue ?',
      'add_player': 'Ajouter un joueur',
      'parent_dashboard_btn': 'Tableau de bord Parent 🔒',
      'attention': 'Attention',
      'impulse_control': 'Contrôle des impulsions',
      'reaction_time': 'Temps de réaction',
      'suggestion': 'Suggestion',
      'recent_sessions': 'Sessions récentes',
      'completed_missions_title': 'Missions terminées',
      'diagnostic_notice': 'Cette application ne fournit pas de diagnostic médical. Les indicateurs sont uniquement destinés à l\'accompagnement.',
      'settings_title': 'Paramètres ⚙️',
      'language_sec': 'Langue 🌍',
      'sound_sec': 'Son 🔊',
      'music_vol': 'Volume Musique',
      'sfx_vol': 'Effets Sonores',
      'voice_instr': 'Instructions vocales',
      'accessibility_sec': 'Accessibilité ♿',
      'reduce_motion': 'Réduire les mouvements',
      'reduce_distractors': 'Réduire les distracteurs',
      'colorblind_mode': 'Mode daltonien',
      'larger_text': 'Texte plus grand',
      'data_sec': 'Données et confidentialité 🔒',
      'clear_all': 'Réinitialiser toutes les données',
      'privacy_policy': 'Politique de confidentialité',
      'game_paused': 'Jeu en pause',
      'mission_complete': 'Mission accomplie ! 🎉',
      'new_record': 'Nouveau record !',
      'stars': 'Étoiles',
      'gems': 'Gemmes',
      'time': 'Temps',
      'accuracy': 'Précision',
      'hints_used': 'Indices utilisés',
      'accuracy_great': 'Excellent !',
      'accuracy_good': 'Bon',
      'accuracy_practice': 'À pratiquer',
      'dark_room_title': 'Chambre noire',
      'dark_room_desc': 'La chambre est sombre. Peux-tu trouver un moyen d\'allumer la lumière ?',
      'dark_room_goal': '💡 Allume la lumière',
      'robot_room_title': 'Laboratoire du robot',
      'robot_room_desc': 'Le robot est hors tension. Donne-lui de l\'énergie en connectant la batterie au câble !',
      'robot_room_goal': '🤖 Alimente le robot',
      'door_room_title': 'Pièce de la porte',
      'door_room_desc': 'La porte est verrouillée ! Trouve la clé cachée et déverrouille-la.',
      'door_room_goal': '🔑 Trouve la clé et ouvre la porte',
      'skills': 'Compétences',
      'skill_attention': '🎯 Attention',
      'skill_logic': '🧠 Logique',
      'skill_focus': '⚡ Concentration',
      'skill_memory': '💾 Mémoire',
      'skill_planning': '🗺 Planification',
      'seconds': 's',
      'hint_dark_room': '💡 Indice : Appuie sur l\'interrupteur électrique pour allumer la lampe !',
      'hint_robot_room': '💡 Indice : Appuie sur la batterie, puis sur le câble d\'alimentation !',
      'hint_door_room': '💡 Indice : Appuie sur la boîte en bois pour trouver la clé, puis sur la clé, puis sur la porte !',
      'hint_button': 'Indice',
      'congratulations': 'Super concentration !',
      'pet_upgrade': 'Améliorer l\'animal',
      'my_treasures': 'Mes trésors ✨',
      'skins_tab': 'Skins 🎨',
      'rooms_tab': 'Pièces 🏠',
      'pets_tab': 'Animaux 🐾',
      'equipped': 'Équipé',
      'use': 'Utiliser',
      'locked': 'Verrouillé',
      'improving': '↑ S\'améliore',
      'steady': '→ Stable',
      'great': '↑ Super',
      'parent_pin_prompt': 'Entrez le PIN parent pour accéder au tableau de bord',
      'invalid_pin': 'PIN invalide. Réessayez !',
      'keep_trying': 'Encore un effort ! 💪',
      'practice_message': 'La pratique nous aide à renforcer notre concentration !',
      'go_to_map': 'Voir la carte du monde',
      'play_again': 'Rejouer',
      'try_again': 'Réessayer',
    },
    'ar': {
      'app_title': 'MindSpark Quest',
      'splash_subtitle': 'مغامرة للعقول الفضولية',
      'explore_rooms_title': 'استكشف غرفاً سحرية',
      'explore_rooms_sub': 'كل غرفة تحتوي على لغز بانتظارك!',
      'solve_puzzles_title': 'حل ألعاباً مسلية',
      'solve_puzzles_sub': 'ابحث عن الأشياء المناسبة وأضئ عالمك الخاص!',
      'earn_rewards_title': 'اكسب النجوم والجوائز',
      'earn_rewards_sub': 'اجمع النجوم، وافتح الغرف، وصمم عالمك الفريد!',
      'next': 'التالي',
      'back': 'رجوع',
      'get_started': 'ابدأ الآن',
      'lets_go': 'هيا بنا!',
      'resume': 'استئناف',
      'restart': 'إعادة اللعب',
      'back_to_map': 'العودة للخريطة',
      'parent_setup': 'إعدادات أولياء الأمور',
      'parent_consent_title': 'خصوصية طفلك تهمنا',
      'parent_consent_desc': 'يقوم MindSpark Quest بحفظ جميع البيانات محلياً على هذا الجهاز. لا يتم مشاركة أي معلومات شخصية عبر الإنترنت. هذا التطبيق ليس أداة للتشخيص الطبي.',
      'parent_consent_check': 'أفهم ذلك وأوافق على استخدام طفلي لهذا التطبيق.',
      'create_pin_title': 'إنشاء رمز PIN للوالدين',
      'create_pin_subtitle': 'يحمي هذا الرمز لوحة تحكم أولياء الأمور',
      'create_profile_title': 'إنشاء حساب للطفل',
      'whats_your_name': 'ما هو اسمك؟',
      'age': 'العمر',
      'language': 'اللغة',
      'start_adventure': 'ابدأ المغامرة!',
      'who_is_playing': 'من يلعب الآن؟',
      'add_player': 'إضافة لاعب',
      'parent_dashboard_btn': 'لوحة تحكم الآباء 🔒',
      'attention': 'الانتباه',
      'impulse_control': 'ضبط الاندفاع',
      'reaction_time': 'زمن الاستجابة',
      'suggestion': 'نصيحة توجيهية',
      'recent_sessions': 'الجلسات الأخيرة',
      'completed_missions_title': 'المهمات المنجزة',
      'diagnostic_notice': 'لا يقدم هذا التطبيق أي تشخيص طبي. المؤشرات المعروضة هي للدعم والتوجيه السلوكي فقط.',
      'settings_title': 'الإعدادات ⚙️',
      'language_sec': 'اللغة 🌍',
      'sound_sec': 'الأصوات 🔊',
      'music_vol': 'مستوى الموسيقى',
      'sfx_vol': 'المؤثرات الصوتية',
      'voice_instr': 'الإرشادات الصوتية',
      'accessibility_sec': 'إمكانية الوصول ♿',
      'reduce_motion': 'تقليل الحركة',
      'reduce_distractors': 'تقليل مشتتات الانتباه',
      'colorblind_mode': 'وضع عمى الألوان',
      'larger_text': 'تكبير حجم الخط',
      'data_sec': 'البيانات والخصوصية 🔒',
      'clear_all': 'إعادة ضبط كل البيانات',
      'privacy_policy': 'سياسة الخصوصية',
      'game_paused': 'تم إيقاف اللعبة',
      'mission_complete': 'تم إنجاز المهمة بنجاح! 🎉',
      'new_record': 'رقم قياسي جديد!',
      'stars': 'نجوم',
      'gems': 'مجوهرات',
      'time': 'الوقت',
      'accuracy': 'الدقة',
      'hints_used': 'التلميحات المستخدمة',
      'accuracy_great': 'ممتاز!',
      'accuracy_good': 'جيد',
      'accuracy_practice': 'يحتاج إلى تدريب',
      'dark_room_title': 'الغرفة المظلمة',
      'dark_room_desc': 'الغرفة مظلمة وباردة. هل يمكنك العثور على طريقة لإضاءة الغرفة؟',
      'dark_room_goal': '💡 أضئ الغرفة المظلمة',
      'robot_room_title': 'غرفة الروبوت',
      'robot_room_desc': 'الروبوت متوقف عن العمل. اعطه الطاقة عبر توصيل البطارية بالسلك الكهربائي!',
      'robot_room_goal': '🤖 شغّل الروبوت',
      'door_room_title': 'غرفة الباب المغلق',
      'door_room_desc': 'الباب مغلق بإحكام! ابحث عن المفتاح المخفي خلف الصندوق لفتحه.',
      'door_room_goal': '🔑 اعثر على المفتاح وافتح الباب',
      'skills': 'المهارات المستهدفة',
      'skill_attention': '🎯 الانتباه',
      'skill_logic': '🧠 المنطق',
      'skill_focus': '⚡ التركيز',
      'skill_memory': '💾 الذاكرة',
      'skill_planning': '🗺 التخطيط',
      'seconds': 'ثانية',
      'hint_dark_room': '💡 تلميح: انقر على مفتاح الكهرباء المثبت على الجدار لتشغيل المصباح!',
      'hint_robot_room': '💡 تلميح: انقر أولاً على البطارية، ثم انقر على سلك التوصيل الكهربائي!',
      'hint_door_room': '💡 تلميح: انقر على الصندوق الخشبي للعثور على المفتاح، ثم انقر على المفتاح، ثم انقر على الباب!',
      'hint_button': 'مساعدة',
      'congratulations': 'تركيز رائع ومذهل!',
      'pet_upgrade': 'ترقية الحيوان الأليف',
      'my_treasures': 'مقتنياتي الثمينة ✨',
      'skins_tab': 'الأشكال 🎨',
      'rooms_tab': 'الغرف 🏠',
      'pets_tab': 'الحيوانات 🐾',
      'equipped': 'مُجهّز',
      'use': 'تجهيز',
      'locked': 'مغلق',
      'improving': '↑ في تحسن',
      'steady': '→ مستقر',
      'great': '↑ ممتاز',
      'parent_pin_prompt': 'أدخل رمز الوالدين للوصول إلى لوحة التحكم',
      'invalid_pin': 'رمز غير صحيح، حاول مجدداً!',
      'keep_trying': 'استمر في المحاولة! 💪',
      'practice_message': 'الممارسة تساعدنا على تقوية عضلات التركيز!',
      'go_to_map': 'الذهاب إلى الخريطة',
      'play_again': 'العب مرة أخرى',
      'try_again': 'حاول مرة أخرى',
    }
  };

  static String get(String key, String lang) {
    if (!_localizedValues.containsKey(lang)) {
      lang = 'en';
    }
    return _localizedValues[lang]?[key] ?? _localizedValues['en']?[key] ?? key;
  }

  static TextDirection getDirection(String lang) {
    return lang == 'ar' ? TextDirection.rtl : TextDirection.ltr;
  }
}
